### PR TITLE
Replace premailer with juice css inliner

### PR DESCRIPTION
**Pull request by leemunroe**
Replaces premailer gem, which is ruby, with juice, node.js.

This should also remove dependency for other gems and Xcode command line tools.

### CODE REVIEW

**Comment by leemunroe** [comment]
Todo:
* Plain text version
* HTML table attributes e.g. cellpadding, cellspacing

**Comment by leemunroe** [comment]
@jrit Is it possible to set table cellpadding and cellspacing attributes automagically to "0" with Juice?

**Comment by jrit** [comment]
Juice doesn't process either right now. Those properties don't have a real clean CSS equivalent. Would providing a default CSS with `td{ margin: 0; padding: 0; }` be enough, or are there clients that will still render padding by default?

**Comment by leemunroe** [comment]
@jrit Thanks. I think I can get away with manually adding cellpadding and cellspacing for now. Still seems to render ok. Cheers.

image

**Pull request merged**
