### PR TITLE
Handlebars components over helpers + examples

### PR DESCRIPTION
**Pull request by taeo**
Using components (handlebars partials) is easier and more natural for most designers than writing javascript based helper functions.

__This PR__: 
* Adds notices and dividers components (sass + partial)
* Adds a template that details available components.
* Ignores compiled css in > `src/css`

### CODE REVIEW

**Comment by leemunroe** [comment]
@taeo This looks awesome btw! Just need some time this week to review and test.

**Comment by taeo** [comment]
@leemunroe - Right on! Hit me back with any feedback / questions once you've had time to review.

**Comment by leemunroe** [comment]
I like this direction. I think you're right about it being more natural.

1. Looks like there's an issue in the responsive view for components.html. Didn't get a chance to dig deeper.
image

2. Noticing some issues in Outlook 2013 and Outlook.com when previewed in Litmus. Most likely a margin issue.
image

3. Do you want to go ahead and remove `src/css/main.css` from the repo?

4. Consider removing `/helpers` and updating the readme.

**Comment by taeo** [comment]
@leemunroe - Thanks for feedback / suggestions.
The first issue was word-break related with the long path in the `code` tag.

These latest updates should cover all your points. :beers:

**Comment by taeo** [comment]
:+1:

**Pull request merged**
