### PR TITLE
Added Salesforce Pardot variables in .yml file. 

### PR DESCRIPTION
**Pull request by xavisavvy**
Added Salesforce Pardot email variables as a helper for faster template creation.

### CODE REVIEW

**Comment by leemunroe** [comment]
Nice one. Does Pardot have an API  / Grunt task that would enable sending these templates to their system?

**Comment by xavisavvy** [comment]
I believe this one looks feature complete:
https://www.npmjs.com/package/pardot#email

Here is the official non-npm documentation for pardot as well for sending emails:
http://developer.pardot.com/kb/api-version-3/emails/#supported-operations_1

**Comment by xavisavvy** [comment]
Do you think there is any interest in a mailchimp yml file as well?

**Comment by leemunroe** [comment]
@xavisavvy Definitely I think these would be useful. Now that grunt tasks have their own file in `/grunt` and we have `aliases.yaml` I think that lessens the risk of cluttering the repo.

**Pull request merged**
