### PR TITLE
update for changes in mailgun api

### LINKED ISSUE #83: Mailgun no longer working
Firstly thank you so much for this amazing workflow, it has made my life so much easier.

The last month or so I have noticed the mailgun task is no longer working. I have done some digging around and it would seem mailgun have updated their API but unfortunately I have not been successful in updating and changing this within the workflow. If its any help windows 10 throws a 301 error and OSX appears to send the email but it doesnt work.

Many thanks.

### PR DESCRIPTION
**Pull request by markhuge**
@leemunroe updated upstream code to fix #83. 

I don't have accounts on all the services in the workflow, so haven't tested end to end. Plz try it out and let me know if you run into any issues.

### CODE REVIEW

**Comment by leemunroe** [comment]
@markhuge Thanks for doing this. 

Unfortunately I wasn't able to get this to work. Played around with it for a while running your branch but didn't see any logs come in. Tried creating a new project with just a gruntfile and grunt-mailgun but no luck either. Tried creating a new Mailgun account and adding a verified email but no luck. Any other ideas what it could be?

**Comment by markhuge** [comment]
@leemunroe are there any errors in the console output?

**Comment by leemunroe** [comment]
All looks good in output

```
➜  grunt-mailgun grunt mailgun -v
Initializing
Command-line options: --verbose

Reading "gruntfile.js" Gruntfile...OK

Registering Gruntfile tasks.
Initializing config...OK

Registering "grunt-mailgun" local Npm module tasks.
Reading /Users/lee/Sites/tmp/grunt-mailgun/node_modules/grunt-mailgun/package.json...OK
Parsing /Users/lee/Sites/tmp/grunt-mailgun/node_modules/grunt-mailgun/package.json...OK
Loading "mailgun.js" tasks...OK
+ mailgun
Loading "gruntfile.js" tasks...OK
>> No tasks were registered or unregistered.

Running tasks: mailgun

Running "mailgun" task

Running "mailgun:marketingTemplates" (mailgun) task
Verifying property mailgun.marketingTemplates exists in config...OK
Files: test.html
Reading test.html...OK

Done.
```

**Comment by VanGTO** [comment]
So I've also tried applying the changes in the PR:

- grunt/mailgun.js
- package.json
- Also added the corresponding "domain" entry to the secrets.json file
- Didn't update the readme.md as didn't seem necessary at this point for my test.

The test send appears to go through fine in terminal. However, still no dice in the logs.

Here's my console output:

`Craigs-MacBook-Pro:mailgun-workflow craig$ grunt mailgun -v
Initializing
Command-line options: --verbose

Reading "Gruntfile.js" Gruntfile...OK

Registering Gruntfile tasks.
Reading secrets.json...OK
Parsing secrets.json...OK
Initializing config...OK

Registering "grunt-assemble" local Npm module tasks.
Reading /Projects/mailgun-workflow/node_modules/grunt-assemble/package.json...OK
Parsing /Projects/mailgun-workflow/node_modules/grunt-assemble/package.json...OK
Loading "assemble.js" tasks...OK
+ assemble

Registering "grunt-autoprefixer" local Npm module tasks.
Reading /Projects/mailgun-workflow/node_modules/grunt-autoprefixer/package.json...OK
Parsing /Projects/mailgun-workflow/node_modules/grunt-autoprefixer/package.json...OK
Loading "autoprefixer.js" tasks...OK
+ autoprefixer

Registering "grunt-aws-s3" local Npm module tasks.
Reading /Projects/mailgun-workflow/node_modules/grunt-aws-s3/package.json...OK
Parsing /Projects/mailgun-workflow/node_modules/grunt-aws-s3/package.json...OK
Loading "aws_s3.js" tasks...OK
+ aws_s3

Registering "grunt-cdn" local Npm module tasks.
Reading /Projects/mailgun-workflow/node_modules/grunt-cdn/package.json...OK
Parsing /Projects/mailgun-workflow/node_modules/grunt-cdn/package.json...OK
Loading "grunt-cdn.js" tasks...OK
+ cdn

Registering "grunt-cloudfiles" local Npm module tasks.
Reading /Projects/mailgun-workflow/node_modules/grunt-cloudfiles/package.json...OK
Parsing /Projects/mailgun-workflow/node_modules/grunt-cloudfiles/package.json...OK
Loading "cloudfiles.js" tasks...OK
+ cloudfiles

Registering "grunt-contrib-clean" local Npm module tasks.
Reading /Projects/mailgun-workflow/node_modules/grunt-contrib-clean/package.json...OK
Parsing /Projects/mailgun-workflow/node_modules/grunt-contrib-clean/package.json...OK
Loading "clean.js" tasks...OK
+ clean

Registering "grunt-contrib-imagemin" local Npm module tasks.
Reading /Projects/mailgun-workflow/node_modules/grunt-contrib-imagemin/package.json...OK
Parsing /Projects/mailgun-workflow/node_modules/grunt-contrib-imagemin/package.json...OK
Loading "imagemin.js" tasks...OK
+ imagemin

Registering "grunt-contrib-watch" local Npm module tasks.
Reading /Projects/mailgun-workflow/node_modules/grunt-contrib-watch/package.json...OK
Parsing /Projects/mailgun-workflow/node_modules/grunt-contrib-watch/package.json...OK
Loading "watch.js" tasks...OK
+ watch

Registering "grunt-express" local Npm module tasks.
Reading /Projects/mailgun-workflow/node_modules/grunt-express/package.json...OK
Parsing /Projects/mailgun-workflow/node_modules/grunt-express/package.json...OK

Registering "grunt-parallel" local Npm module tasks.
Reading /Projects/mailgun-workflow/node_modules/grunt-express/node_modules/grunt-parallel/package.json...OK
Parsing /Projects/mailgun-workflow/node_modules/grunt-express/node_modules/grunt-parallel/package.json...OK
Loading "parallel.js" tasks...OK
+ parallel
Loading "express.js" tasks...OK
+ express, express-keepalive, express-restart, express-server, express-start

Registering "grunt-juice-email" local Npm module tasks.
Reading /Projects/mailgun-workflow/node_modules/grunt-juice-email/package.json...OK
Parsing /Projects/mailgun-workflow/node_modules/grunt-juice-email/package.json...OK
Loading "juice.js" tasks...OK
+ juice

Registering "grunt-litmus" local Npm module tasks.
Reading /Projects/mailgun-workflow/node_modules/grunt-litmus/package.json...OK
Parsing /Projects/mailgun-workflow/node_modules/grunt-litmus/package.json...OK
Loading "litmus.js" tasks...OK
+ litmus

Registering "grunt-mailgun" local Npm module tasks.
Reading /Projects/mailgun-workflow/node_modules/grunt-mailgun/package.json...OK
Parsing /Projects/mailgun-workflow/node_modules/grunt-mailgun/package.json...OK
Loading "mailgun.js" tasks...OK
+ mailgun

Registering "grunt-open" local Npm module tasks.
Reading /Projects/mailgun-workflow/node_modules/grunt-open/package.json...OK
Parsing /Projects/mailgun-workflow/node_modules/grunt-open/package.json...OK
Loading "open.js" tasks...OK
+ open

Registering "grunt-parallel" local Npm module tasks.
Reading /Projects/mailgun-workflow/node_modules/grunt-parallel/package.json...OK
Parsing /Projects/mailgun-workflow/node_modules/grunt-parallel/package.json...OK
Loading "parallel.js" tasks...OK
+ parallel

Registering "grunt-replace" local Npm module tasks.
Reading /Projects/mailgun-workflow/node_modules/grunt-replace/package.json...OK
Parsing /Projects/mailgun-workflow/node_modules/grunt-replace/package.json...OK
Loading "replace.js" tasks...OK
+ replace

Registering "grunt-sass" local Npm module tasks.
Reading /Projects/mailgun-workflow/node_modules/grunt-sass/package.json...OK
Parsing /Projects/mailgun-workflow/node_modules/grunt-sass/package.json...OK

node-sass	3.13.1	(Wrapper)	[JavaScript]
libsass  	3.3.6	(Sass Compiler)	[C/C++]

Loading "sass.js" tasks...OK
+ sass
Loading "Gruntfile.js" tasks...OK
+ default, rsupload, s3upload, send, serve

Running tasks: mailgun

Running "mailgun" task

Running "mailgun:mailer" (mailgun) task
Verifying property mailgun.mailer exists in config...OK
Files: [no src]
Sent mailgun msg to testing@m...`

I also reached out to mailgun support and here's their response:

> Hello Craig,
> 
> Thank you for contacting Mailgun support. 
> 
> We haven't made any updates to the API.
> 
> I was able to successfully send out a messages using curl:
> 
> ~~~
> $ curl -s --user api:yourapikeyhere https://api.mailgun.net/v2/mail.MYDOMAIN.com/messages -F from='Sample Email <me@mail.MYDOMAIN.com>' -F to=mgbox01@gmail.com -F subject='Test Message' -F text='Testing some Mailgun awesomness!'
> {
>   "id": "<20170313061320.126621.18660.EA1B35D0@mail.MYDOMAIN.com>",
>   "message": "Queued. Thank you."
> ~~~
> 
> ~~~
> 13.03.2017 06:13	Delivered: me@mail.MYDOMAIN.com → mgbox01@gmail.com 'Test Message' Server response: 250 OK	
> 	
> 13.03.2017 06:13	Accepted: me@mail.MYDOMAIN.com → mgbox01@gmail.com 'Test Message'
> ~~~
> 
> Thanks,
> Raquel@MG

So MG API is working via other means.

**Comment by rwillwerth** [comment]
I tried to implement. I'm getting a ">> SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode" error.

**Comment by markhuge** [comment]
@leemunroe Apologies, I haven't used grunt in years and didn't remember how to unit test grunt plugins. I didn't bother writing new tests for this and it totally bit me >:D. 

 Its working for email templates on my end, so you should be good to go.

**Comment by VanGTO** [comment]
No dice for me. I've followed changes:

Added to grunt/mailgun.js
`domain: '<%= secrets.mailgun.domain %>', // See README for secrets.json or replace this with your own email domain`

Added to secrets.json
`"domain": "mail.my-domain-name.com",` NB - tried naked domain, and also with http:// unsuccessfully

Added to package.json
`"grunt-mailgun": "^2.0.1",` NB removed 1.0.1 and then 2.0.0

As i say, still not working for me.

**Comment by romanlelek** [comment]
I have just tested it and it works for me. Thank you.

Secrets.json - I have added my domain (without http): mydomain.com
grunt/mailgun.js - I have added :  domain: '<%= secrets.mailgun.domain %>',

and updated package json to ^2.0.1 (I have originally tried previous non-working version too) and of course sudo npm install.

Running "mailgun:mailer" (mailgun) task
Sent msg to me@mydomain.com
{ id: '<20170315155421.34295.99154....@mydomain.com>',
  message: 'Queued. Thank you.' }

Thank you.

Best regards,
Roman

**Comment by leemunroe** [comment]
Awesome working for me now. Thanks @markhuge

**Pull request merged**
